# Generated by Django 3.1.1 on 2020-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('ingredient_1', models.CharField(max_length=30)),
                ('ingredient_2', models.CharField(max_length=30)),
                ('ingredient_3', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
    ]
